from collections.abc import Callable, Sequence

from clonway_cockpit.signals.model import Signal

def scan_horizon(fn: Callable[..., Sequence[Signal]]) -> Callable[..., Sequence[Signal]]: ...
def compose_horizon(fn: Callable[..., Sequence[Signal]]) -> Callable[..., tuple[Signal, ...]]: ...
